### ISSUE TITLE
Improve parameter-values

### ISSUE THREAD

**Issue by cschwaderer** [chrisguttandin/angular-prerender#113]
Since Angular prerendering in general and angular-prerenderer specifially finally works for me, I now tried to care about the details. With no luck so far. It is great that angular-prerenderer offers the param `parameter-values`, but its usage is either not well documented or it doesn't work for my scenario.

Consider these route definitions

```
const routes: Routes = [
    {
        path: "/bar",
        component: HomeComponent
    },
    {
        path: "/route-i-want-to-prerender/:id/:title",
        component: WhatEver
    },
    {
        path: "/route-i-do-not-want-to-prerender/:id/:title",
        component: AnotherOne,
    }
]
```

First problem: Params have the same name across routes, but there is just one route for which I want to pass params (or I want to pass different params per route).
Second problem: There are multiple params per route. If I pass the params like 
`'{":id":["1","2","3"],":title":["foo1","foo2","foo3"]`
I expect the routes below to be prerendered

- /route-i-want-to-prerender/1/foo1
- /route-i-want-to-prerender/2/foo2
- /route-i-want-to-prerender/3/foo3

However, instead of 3 routes, angular-prerenderer produced 9. I don't get exactly what happens here, but it is wrong for my use case.

Finally, I'd prefer to be able to pass a JSON file (or a path pointing to a JSON file, to be more precise) instead of a string. That way, you get rid of escaping problems and you won't run into any length restriction issues on the command line.

In my opinion, the expected structure of that JSON file should be something like this
```
{
    "/route-i-want-to-prerender/:id/:title": [
        { ":id": "1", ":title": "foo1" },
        { ":id": "2", ":title": "foo2" },
        { ":id": "3", ":title": "foo3" }
    ],
    "/another-route-i-want-to-prerender/:id/:title": [
        { ":id": "4", ":title": "bar4" },
        { ":id": "5", ":title": "bar5" },
        { ":id": "6", ":title": "bar6" }
    ],
}
```

**Comment by chrisguttandin** [comment]
Hi @cschwaderer,

thanks for filing this issue? Unfortunately the `--parameter-values` argument is not really usable for your use case. It currently renders each route with all possible permutations. And as you discovered the parameter values can't be scoped to a specific route.

I like the schema that you proposed. Building up on this I would propose the following.

* The current functionality keeps the same if you specify the JSON as this it will render 9 routes:
```json
{
    ":id": ["1","2","3"],
    ":title": ["foo1","foo2","foo3"]
}
```
* Additionally it should be possible to group parameters. This will only render 3 routes:
```json
[
    {":id":["1"], ":title":["foo1"]},
    {":id":["2"], ":title":["foo2"]},
    {":id":["3"], ":title":["foo3"]}
]
```
* And finally as you proposed it should be possible to scope parameters by routes:
```json
{
    "/route-i-want-to-prerender/:id/:title": [
        { ":id": "1", ":title": "foo1" },
        { ":id": "2", ":title": "foo2" },
        { ":id": "3", ":title": "foo3" }
    ],
    "/another-route-i-want-to-prerender/:id/:title": [
        { ":id": "4", ":title": "bar4" },
        { ":id": "5", ":title": "bar5" },
        { ":id": "6", ":title": "bar6" }
    ],
}
```

This means a property of the JSON object can be either a parameter (`":id"`) or a route (`"/x/y/z"`). If it starts with colon it's considered to be a parameter and if it starts with a slash it's considered to be a path.

The values must be either a string or an array of strings.

Does that sound reasonable to you?

**Comment by cschwaderer** [comment]
@chrisguttandin Thanks for reacting so fast! Yes, that sounds very reasonable to me in general.

Just one question for your second case:

```
[
    {":id":["1"], ":title":["foo1"]},
    {":id":["2"], ":title":["foo2"]},
    {":id":["3"], ":title":["foo3"]}
]

```
Why do the values need to be an array here? Wouldn't flat values like

```
[
    {":id":"1", ":title":"foo1"},
    {":id":"2", ":title":"foo2"},
    {":id":"3", ":title":"foo3"}
]
```

be better and clearer in this case?

**Comment by chrisguttandin** [comment]
Oh, sorry for not pointing that out. I think both should work. I'm trying to get the update done by the end of the week.

**Comment by chrisguttandin** [comment]
Hi @cschwaderer, v5.3 should support your use case now. Please let me know if you run into any issues.

**Comment by chrisguttandin** [comment]
I also updated the readme. Could you please have a look and tell me if you think it sufficiently explains how `--parameter-values` work.

**Comment by cschwaderer** [comment]
Thank you so much for implementing this to fast! Really helps me!

Now, first of all, just one question.
Instead of (as stated above)

```
{
    "/route-i-want-to-prerender/:id/:title": [
        { ":id": "1", ":title": "foo1" },
        { ":id": "2", ":title": "foo2" },
        { ":id": "3", ":title": "foo3" }
    ],
    "/another-route-i-want-to-prerender/:id/:title": [
        { ":id": "4", ":title": "bar4" },
        { ":id": "5", ":title": "bar5" },
        { ":id": "6", ":title": "bar6" }
    ],
}
```
the expected input is now

```
[
  { "/route-i-want-to-prerender/:id/:title": { ":id": "1", ":title": "foo1" }},
  { "/route-i-want-to-prerender/:id/:title": { ":id": "2", ":title": "foo2" }},
  { "/route-i-want-to-prerender/:id/:title": { ":id": "3", ":title": "foo3" }},
  { "/another-route-i-want-to-prerender/:id/:title": { ":id": "4", ":title": "bar4" }},
  { "/another-route-i-want-to-prerender/:id/:title": { ":id": "5", ":title": "bar5" }},
  { "/another-route-i-want-to-prerender/:id/:title": { ":id": "6", ":title": "bar6" }}
]
```

Is that on purpose for internal reasons? Because for the user, it's a little bit more verbose this way.

Additionally, since you asked me if the readme is clear enough, I'd say your example for this case is a somehow incomplete.
First of all, it's confusing because the routes used as an example do not contain params. Also, using at least two values per route would make clearer how it should look like.
My suggestion would be:

```
[{"/shirts/:id":{":id":"shirt-a"},{"/shirts/:id":{":id":"shirt-b"},"/shoes/:id":{":id":"shoe-a"}},"/shoes/:id":{":id":"shoe-b"}}]
```

As a last point: When passing wrong formatted values for `--parameter-values`, angular-prerenderer doesn't tell exactly what is wrong right now. You might want to think about including some kind of JSON schema check (I personally use https://github.com/tdegrunt/jsonschema for such cases) in order to provide more detailed errors.

**Comment by chrisguttandin** [comment]
I'm glad it helps you.

Both of your examples should work. You could even get rid of a couple of more characters:

```json
{
    "/route-i-want-to-prerender": [
        { ":id": "1", ":title": "foo1" },
        { ":id": "2", ":title": "foo2" },
        { ":id": "3", ":title": "foo3" }
    ],
    "/another-route-i-want-to-prerender": [
        { ":id": "4", ":title": "bar4" },
        { ":id": "5", ":title": "bar5" },
        { ":id": "6", ":title": "bar6" }
    ]
}
```

It's only necessary to specify the portion of the route which is different from the others. I also allowed another schema to avoid the additional array in case there is only one set of parameter values per route. In that case you could use something like this... 

```json
{
    "/route-i-want-to-prerender": { ":id": "1", ":title": "foo1" },
    "/another-route-i-want-to-prerender": { ":id": "4", ":title": "bar4" }
}
```

Please let me know if that doesn't work. In that case I introduced a bug.

Adding a JSON schema validation is an excellent idea. I'll put it on the todo list.

I thought it makes the README simpler when I only use one parameter but I can see why that wasn't a good idea. Thanks for your feedback.
