### ISSUE TITLE
Atob is not defined

### ISSUE THREAD

**Issue by Drevoed** [chrisguttandin/angular-prerender#120]
When using angular-prerender with angular 9 application, it crashes on 

```js
.../node_modules/zone.js/dist/zone-node.js:192
throw error;

ReferenceError: atob is not defined
```

**Comment by chrisguttandin** [comment]
Hi Kirill, is it possible that you're using `atob` somewhere in your Angular app or that it's used by one of your dependencies? `atob` and `btoa` are not available in Node.js.

**Comment by Drevoed** [comment]
Yes, I do indeed use atob in one route, but it seems like my options here are limited to excluding a route, right?

**Comment by chrisguttandin** [comment]
You could create a little helper which uses the API of the current platform.

```ts

**Comment by Drevoed** [comment]
Thank you!
