### ISSUE TITLE
Please install ts-evaluator instead

### ISSUE THREAD

**Issue by splincode** [chrisguttandin/angular-prerender#127]
![image](https://user-images.githubusercontent.com/12021443/123667984-5414f480-d843-11eb-8ecd-33893f26ed12.png)

**Comment by chrisguttandin** [comment]
Hi @splincode,

the error should get thrown if either `@angular/core`, `@angular/platform-server` or `zone.js` is missing. Do you have all those installed?

Are you able to share more details about your project?

**Comment by HamzaMoiyadi** [comment]
Hi, I am facing a similar issue as well

Here is my terminal's screenshot
![Screenshot from 2022-08-30 18-29-44](https://user-images.githubusercontent.com/17302799/187443212-952f0a78-f904-4e53-ab02-ff996a77a7ab.png)

**Comment by chrisguttandin** [comment]
Hi @HamzaMoiyadi which versions of Angular and RxJS are you currently using in your project? angular-prerender still requires Angular v13.

**Comment by HamzaMoiyadi** [comment]
Hey @chrisguttandin , I'm using Angular 14. I think that's the issue, as you said.

**Comment by chrisguttandin** [comment]
Hi @HamzaMoiyadi, I finally updated angular-prerender for Angular v14. Version 11+ of angular-prerender is now compatible with Angular v14.
