### ISSUE TITLE
MODULE_MAP instance loaded by angular-prerender is not the same as the one used by the server module

### ISSUE THREAD

**Issue by jessezhang91** [chrisguttandin/angular-prerender#83]
First of all, thank you so much for creating this repo!

When I bumped `angular-prerender` from 4.1.5 to latest, I ran into this error:
`NullInjectorError: No provider for InjectionToken MODULE_MAP!`

After digging in a little bit, I think it's related to the deferred loading of the `@nguniversal/module-map-ngfactory-loader` (in particular, https://github.com/chrisguttandin/angular-prerender/blob/master/src/functions/load-peer-dependencies.ts#L39).

I believe how it's being executed there, the `MODULE_MAP` from `@nguniversal/module-map-ngfactory-loader` (https://github.com/angular/universal/blob/991472d1abe721d2ebba8c5faf89f7177a95bc68/modules/module-map-ngfactory-loader/src/module-map-ngfactory-loader.ts#L22) is being recreated. The one that is used in `ModuleMapLoaderModule` is the existing `MODULE_MAP` and DI isn't matching the two together.

**Comment by chrisguttandin** [comment]
Hi @jessezhang91, thanks a lot for reporting this. It was definitely not my intention to break the DI.

Do you by chance have a small example which surfaces the error that I could use to test this?

**Comment by chrisguttandin** [comment]
I think I found a way to reproduce the problem: https://github.com/chrisguttandin/angular-prerender/commit/be03c195358fbfd8c68d2131b34d821aaf3469cf Modifying the the AppServerModule as described [here](https://github.com/angular/universal/blob/master/modules/module-map-ngfactory-loader/README.md) did already cause angular-prerender to fail.

I removed @nguniversal/module-map-ngfactory-loader as a dependency of this package. It will now only be used if it is installed as peer dependency.

I hope this solves your problem as well. Please let me know if that's not the case.

**Comment by jessezhang91** [comment]
Sorry for the late response. I just bumped it up in my project and it all prerendered properly. Thank you!
