### ISSUE TITLE
Basic project example seems to be missing a step

### ISSUE THREAD

**Issue by nassimm** [chrisguttandin/angular-prerender#93]
Hi,

I've been playing with this package a bit, it's really cool

It'll be obvious for people who are used to modern builds, but the basic project example seems to omit the "npm install" step, which is necessary to do before the "ng build" step.

Thanks for the new toy to play with, cheers

**Comment by chrisguttandin** [comment]
Hi @nassimm, thanks for the nice words.

I'm not sure which install is missing? Do you mean an explicit installation of the Angular CLI? That should be covered by running it via `npx`.

**Comment by nassimm** [comment]
Hi, so the issue is that following the example project gives this error on Windows:
![image](https://user-images.githubusercontent.com/7755314/68719603-c5d7f600-05ac-11ea-8945-68c63d68b557.png)
I can reproduce this consistently by just following the install steps
Running npm install before continuing fixes the problem

**Comment by chrisguttandin** [comment]
Thanks for providing further details. I'm not a Windows user which is probably why I never ran into it so far.

But I still don't fully understand why that happens. Is this the order of commands as they work for you?

```sh
npx @angular/cli new universe --routing
cd universe
ng generate universal --client-project universe
npm install angular-prerender --save-dev

npm install

ng build
ng run universe:server
npx angular-prerender
```

I wonder what the additional `npm install` command does. When creating a new project the Angular CLI should take care of installing all dependencies (except of angular-prerender of course). It's also strange that `ng generate` works but `ng build` does not. Do you have an idea what could cause this?

**Comment by chrisguttandin** [comment]
I'm closing this now because of the lack of further feedback. Feel free to reopen this issue if the problem still persists on your end.
